voj-backend:
  version: 2023/10/14
  ip: ${BACKEND_SERVER_IP:127.0.0.1}
  port: ${BACKEND_SERVER_PORT:6688}
server:
  port: ${voj-backend.port}
  servlet:
    encoding:
      force: true

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_URL:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        group: DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - nacos:voj-${spring.profiles.active}.yml
      - nacos:voj-remote.yml
  profiles:
    active: @profiles.active@

  # 配置文件上传限制
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  redis:
    host: ${voj.redis.host}
    port: ${voj.redis.port}
    password:
    # 连接超时时间（毫秒）
    timeout: 3000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 50
      # 连接池中的最小空闲连接
      min-idle: 10
  datasource:
    username: ${voj.db.username}
    password: ${voj.db.password}
    url: jdbc:mysql://${voj.db.host}:${voj.db.port}/${voj.db.name}?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    min-idle: 20 # 最小连接池数量
    maxActive: 200 # 最大连接池数量
    maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
    timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
    minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
    validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
    testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
    testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    poolPreparedStatements: true # 开启PSCache
    maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
    connectionErrorRetryAttempts: 3 # 连接出错后再尝试连接三次
    breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
    timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
    asyncInit: true # 异步初始化策略
    remove-abandoned: true # 是否自动回收超时连接
    remove-abandoned-timeout: 1800 # 超时时间(以秒数为单位)
    transaction-query-timeout: 6000 # 事务超时时间
    filters: stat,wall,log4j #数据库日志
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    encoding: UTF-8

shiro-redis:
  enabled: true
  redis-manager:
    host: ${voj.redis.host}:${voj.redis.port}
    password:

mybatis-plus:
  mapper-locations: classpath*:com/simplefanc/voj/backend/mapper/xml/**Mapper.xml
  type-aliases-package: com.simplefanc.voj.common.pojo.entity
  configuration:
    cache-enabled: false
  # 关闭打印 mybatis-plus 的 LOGO
  global-config:
    banner: false

logging:
  level:
    com.alibaba.nacos: error
    root: info
  #  config: classpath:logback-spring.xml
  file:
    path: ./log

# 消费者将要去访问的微服务名称（注册成功进入nacos的微服务提供者）
service-url:
  name: voj-judger # 服务名

filepath:
  testcase-base-folder: "/voj/testcase"
  user-avatar-folder: "/voj/file/avatar"
  home-carousel-folder: "/voj/file/carousel"
  markdown-file-folder: "/voj/file/md"
  problem-file-folder: "/voj/file/problem"
  contest-text-print-folder: "/voj/file/contest_print"
  testcase-tmp-folder: "/voj/file/zip"
  file-download-tmp-folder: "/voj/file/zip/download"
  contest-ac-submission-tmp-folder: "/voj/file/zip/contest_ac"
  img-api: "/api/public/img/"
  file-api: "/api/public/file/"

voj:
  cache:
    allowNull: true
    initialCapacity: 128
    maximumSize: 1024
    # Caffeine过期时间
    expireAfterWrite: 30
    # Redis缓存过期时间
    redisExpire: 60

---
spring:
  config:
    activate:
      on-profile: dev
filepath:
  testcase-base-folder: "~/voj/testcase"
  user-avatar-folder: "~/voj/file/avatar"
  home-carousel-folder: "~/voj/file/carousel"
  markdown-file-folder: "~/voj/file/md"
  problem-file-folder: "~/voj/file/problem"
  contest-text-print-folder: "~/voj/file/contest_print"
  testcase-tmp-folder: "~/voj/file/zip"
  file-download-tmp-folder: "~/voj/file/zip/download"
  contest-ac-submission-tmp-folder: "~/voj/file/zip/contest_ac"
  img-api: "~/api/public/img/"
  file-api: "~/api/public/file/"